"use client";

import SideNav from "@/components/sideNav";
import "./globals.css";
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "swiper/css/bundle";
import { useState } from "react";
import { GiHamburgerMenu } from "react-icons/gi";
import { byellow } from "@/assets/colors";
// import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [display, setDisplay] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full max-w-[1728px] overflow-hidden ">
          <div
            className={`${
              display ? "" : "hidden"
            } md:flex md:w-1/5 flex-col h-screen`}>
            <button
              className="absolute top-1 left-1 md:hidden z-[500]"
              onClick={(e) => setDisplay(!display)}>
              <GiHamburgerMenu size={40} color={byellow} />
            </button>
            <div className="w-full">
              <SideNav />
            </div>
          </div>

          <div className=" w-full md:w-4/5">{children}</div>
        </div>
      </body>
    </html>
  );
}
